<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.dlduarte</groupId>
    <artifactId>supple-http-error</artifactId>
    <version>1.1.0</version>

    <name>supple-http-error</name>
    <description>A framework-agnostic Java library for standardizing error modeling, propagation and serialization in backend applications, HTTP APIs and SDKs,
        based on RFC-7807 (Problem Details for HTTP APIs)
    </description>
    <url>https://github.com/dlduarte/supple-http-error</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/dlduarte/supple-http-error.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:dlduarte/supple-http-error.git</developerConnection>
        <url>https://github.com/dlduarte/supple-http-error</url>
        <tag>HEAD</tag>
    </scm>

    <developers>
        <developer>
            <id>dlduarte</id>
            <name>David Duarte</name>
            <email>dlduarte.dev@gmail.com</email>
        </developer>
    </developers>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <distributionManagement>
        <repository>
            <id>nexus</id>
            <url>https://nexus.softensistemas.com.br/repository/maven-releases</url>
        </repository>
    </distributionManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.42</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.1.1</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.20.2</version>
        </dependency>
    </dependencies>
</project>